import Link from "next/link";

import { WorldMap, type WorldMapMarker } from "@/components/ui/world-map";
import { kalingaStoneBrand } from "@/config/kalingastone";
import points from "@/config/global-presence-points.json";

/**
 * Global presence - the dotted world map closing the home page (owner
 * spec, 2026-08-17): every KalingaStone market from the official
 * presence list marked in Pastel Green, the Silvassa plant and the
 * Al Sajaa/Dubai stock point in Onyx, and Pine supply arcs drawn from
 * the plant to Dubai and out to the regions. Marker coordinates are
 * generated by scripts/build-world-map.mjs (grid-snapped by dotted-map)
 * so pins always sit on landmass dots. Server component; the map
 * overlay is the client island.
 */

const markers = points.markers as WorldMapMarker[];
const byLabel = new Map(markers.map((m) => [m.label, m]));

function marker(label: string): WorldMapMarker {
  const found = byLabel.get(label);
  if (!found) throw new Error(`global-presence: unknown marker "${label}"`);
  return found;
}

const hub = marker("Dubai, UAE");

const arcs = [
  { from: marker("Silvassa, India"), to: hub },
  { from: hub, to: marker("London, United Kingdom") },
  { from: hub, to: marker("New York, USA") },
  { from: hub, to: marker("Sao Paulo, Brazil") },
  { from: hub, to: marker("Johannesburg, South Africa") },
  { from: hub, to: marker("Singapore") },
  { from: hub, to: marker("Sydney, Australia") },
];

export function GlobalPresence() {
  return (
    <section
      aria-label="KalingaStone global presence"
      className="bg-background relative pb-24 lg:pb-32"
    >
      <div className="container-gcb">
        <div className="flex items-baseline justify-between">
          <div>
            <p className="label-gcb text-warm-black/60">Global presence</p>
            <h2 className="font-display text-warm-black mt-3 text-3xl tracking-tight sm:text-5xl">
              One material, {kalingaStoneBrand.countries} countries.
            </h2>
          </div>
          <p className="label-gcb text-warm-black/50 hidden sm:block">
            {markers.length} markets marked
          </p>
        </div>
        <p className="text-warm-black/70 mt-5 max-w-2xl leading-relaxed">
          KalingaStone ships from the Silvassa plant to projects in{" "}
          {kalingaStoneBrand.countries} countries. Global Classic holds the
          UAE line of that network - slabs in stock at Al Sajaa, Sharjah,
          delivered across the whole of the UAE.
        </p>

        <WorldMap
          className="mt-12"
          markers={markers}
          arcs={arcs}
          viewBox={points.viewBox}
        />

        <div className="mt-8 flex flex-wrap items-center gap-3">
          <Link
            href="/kalingastone"
            className="chip-gcb border-warm-black text-warm-black inline-flex items-center rounded-full border px-5 py-2 text-sm"
          >
            The KalingaStone range
          </Link>
          <Link
            href="/contact"
            className="chip-gcb border-warm-black text-warm-black inline-flex items-center rounded-full border px-5 py-2 text-sm"
          >
            Check stock in Al Sajaa
          </Link>
        </div>
      </div>
    </section>
  );
}
