import Link from "next/link";

import { WorldMap, type WorldMapMarker } from "@/components/ui/world-map";
import { kalingaStoneBrand } from "@/config/kalingastone";
import points from "@/config/global-presence-points.json";

/**
 * Global presence - the dotted world map closing the home page (owner
 * spec, 2026-08-17; inverted to the Onyx stage 2026-08-18): every
 * KalingaStone market from the official presence list marked in Marble
 * White, the Silvassa plant and the Al Sajaa/Dubai stock point in
 * Pastel Green, and a GENERAL connectivity mesh - a minimum spanning
 * tree over all markers, so every dot links into one web through its
 * regional neighbours with no hub (owner correction: not radiating
 * from Dubai). Marker coordinates are generated by
 * scripts/build-world-map.mjs (grid-snapped by dotted-map) so pins
 * always sit on landmass dots. Server component; the map overlay is
 * the client island.
 */

const markers = points.markers as WorldMapMarker[];

/** Prim's minimum spanning tree over the projected coordinates - 58
 *  edges connecting all 59 markers through their nearest neighbours.
 *  Computed once at module scope; deterministic. */
function spanningArcs(nodes: WorldMapMarker[]) {
  const arcs: { from: WorldMapMarker; to: WorldMapMarker }[] = [];
  if (nodes.length < 2) return arcs;
  const inTree = new Set<number>([0]);
  const dist2 = (a: WorldMapMarker, b: WorldMapMarker) =>
    (a.x - b.x) ** 2 + (a.y - b.y) ** 2;
  while (inTree.size < nodes.length) {
    let best: { from: number; to: number; d: number } | null = null;
    for (const i of inTree) {
      for (let j = 0; j < nodes.length; j++) {
        if (inTree.has(j)) continue;
        const d = dist2(nodes[i], nodes[j]);
        if (!best || d < best.d) best = { from: i, to: j, d };
      }
    }
    if (!best) break;
    inTree.add(best.to);
    arcs.push({ from: nodes[best.from], to: nodes[best.to] });
  }
  return arcs;
}

const arcs = spanningArcs(markers);

export function GlobalPresence() {
  return (
    <section
      aria-label="KalingaStone global presence"
      className="bg-warm-black grain-gcb relative overflow-hidden py-16 lg:py-6"
    >
      {/* Owner spec 2026-08-18, second pass: no container - the map runs
          the full viewport width; a solid-to-transparent Onyx scrim sits
          OVER the map's upper half so the heading rests on shadow and the
          map emerges from underneath it (reference: the Global Network
          demo). Heading + ONE line only. Below lg the heading stacks
          above the full-bleed map. */}
      <div className="relative">
        <div className="pointer-events-none relative z-10 px-6 text-center lg:absolute lg:inset-x-0 lg:top-[10%]">
          <p className="label-gcb text-ink/60">Global presence</p>
          <h2 className="font-display text-ink mx-auto mt-3 text-3xl tracking-tight sm:text-5xl">
            One material, {kalingaStoneBrand.countries} countries.
          </h2>
          <p className="text-ink/70 mx-auto mt-4 max-w-xl leading-relaxed">
            Made in Silvassa, stocked in Al Sajaa, delivered UAE-wide.
          </p>
        </div>

        <div className="relative mt-10 lg:mt-0 [mask-image:linear-gradient(to_bottom,black,black_86%,transparent)]">
          <WorldMap markers={markers} arcs={arcs} viewBox={points.viewBox} />
          {/* The shadow the heading rests on - covers the map, then
              dissolves so the world surfaces below the text */}
          <div
            aria-hidden
            className="from-warm-black via-warm-black/75 pointer-events-none absolute inset-x-0 top-0 hidden h-[52%] bg-gradient-to-b to-transparent lg:block"
          />
        </div>

        <div className="relative z-10 mt-8 flex flex-wrap items-center justify-center gap-3 px-6 lg:-mt-20">
          <Link
            href="/kalingastone"
            className="chip-gcb border-ink/60 text-ink inline-flex items-center rounded-full border px-5 py-2 text-sm"
          >
            The KalingaStone range
          </Link>
          <Link
            href="/contact"
            className="chip-gcb border-ink/60 text-ink inline-flex items-center rounded-full border px-5 py-2 text-sm"
          >
            Check stock in Al Sajaa
          </Link>
        </div>
      </div>
    </section>
  );
}
