/**
 * FILA product data - every field verbatim or tightly condensed from
 * docs/fila-catalogue.md (FILA Easy Guide Middle East 06-2023 +
 * Company Profile 2024), with printed Guide page numbers. NO PRICES
 * exist in the source. The 15 catalogue flags (docs/fila-catalogue.md
 * section 4) are respected: body pages are authoritative for CLASSIC /
 * LONGLIFE and the CONCRETE pair; no misprints propagate here.
 */

export type FilaCategory =
  | "cleaners"
  | "protectors"
  | "finishing"
  | "ready-to-use";

export type FilaProduct = {
  name: string;
  slug: string;
  category: FilaCategory;
  /** professional or ready to use line */
  line: "professional" | "ready-to-use";
  /** Function line as printed under the name. */
  title: string;
  badges: string[];
  surfaces: string[];
  whatFor: string[];
  advantages: string[];
  packaging: string;
  /** Coverage / dilution rows as printed: [use, dilution, coverage]. */
  coverage: [string, string, string][];
  /** Guide page. */
  page: number;
  indoorOnly?: boolean;
  hasScene: boolean;
  /** Scene contains a before/after pair usable in the slider. */
  beforeAfter?: boolean;
  /** Verbatim quotable line for typographic cards. */
  quote?: string;
};

export const filaProducts: FilaProduct[] = [
  {
    name: "CLEANER PRO", slug: "cleaner-pro", category: "cleaners", line: "professional",
    title: "Professional maintenance for surfaces",
    badges: ["Biodegradable ingredients"],
    surfaces: ["Porcelain and ceramic tiles", "Concrete", "Wood", "Marble, granite and natural stone", "Plastic laminates and LVT", "Linoleum, rubber and PVC", "Terracotta and quarry tiles"],
    whatFor: ["Delicately cleans all types of floors and surfaces", "Does not affect treated and delicate surfaces", "Essential for washing natural stone floors after laying, particularly polished finishes sensitive to strong detergents"],
    advantages: ["It cleans but does not attack", "At 1:200 dilution there is no need to rinse - no residues", "Highly concentrated, usable at various dilutions", "Ideal for maintenance of all waxed surfaces", "Works with scrubber-dryer machines at 1:200", "Ideal for laminates", "Pleasant fragrance", "HACCP-compliant", "Pet safe"],
    packaging: "1 L boxes of 12 - 5 L boxes of 4",
    coverage: [["Maintenance", "1:200", "1500 m2 per litre"], ["Initial stone wash", "1:30", "50 m2 per litre"]],
    page: 5, hasScene: true, quote: "It cleans but does not attack",
  },
  {
    name: "CR10", slug: "cr10", category: "cleaners", line: "professional",
    title: "Cleaner for epoxy residues",
    badges: ["Biodegradable ingredients"],
    surfaces: ["Porcelain tiles", "Glazed ceramic tiles", "Glass mosaic", "Polished quarry tiles"],
    whatFor: ["High viscosity detergent for cleaning epoxy grout residues, stains and streaks from walls and floors", "Ideal for non-absorbent materials such as porcelain, glazed ceramic and glass mosaics"],
    advantages: ["Its viscosity lifts epoxy grout stains and marks", "Effective on significant, consolidated residues", "Does not affect the material", "Easy to apply", "Pleasant almond fragrance"],
    packaging: "1 L boxes of 12",
    coverage: [["Epoxy residue removal", "undiluted", "up to 10 m2 per litre"]],
    page: 6, hasScene: true,
  },
  {
    name: "DETERDEK PRO", slug: "deterdek-pro", category: "cleaners", line: "professional",
    title: "End-of-work cleaning",
    badges: ["Eco Advanced formula", "Biodegradable ingredients"],
    surfaces: ["Porcelain tiles", "Glazed ceramic tiles", "Acid-resistant materials", "Terracotta", "Quarry tiles"],
    whatFor: ["Detergent for end-of-installation washing - removes post-application deposits and stubborn inorganic dirt", "Eliminates saline efflorescence from terracotta and limescale from floors, showers and sanitary fittings", "Simultaneous descaling and cleaning action from its high surfactant content, without attacking the material", "Effective against rust traces; helps remove engobe marks from ceramic and porcelain"],
    advantages: ["Eco-advanced formula: ingredients biodegradable up to 98%, innovative phosphate-free formulation", "Controlled long-lasting action improves washing efficacy", "Effective on newly formulated admixed cement grouts; EPA-compliant surfactants", "Buffered acid - no harmful fumes for user or environment", "Does not alter the appearance or colour of materials, or ruin aluminium and steel profiles", "Cleans and removes deposits according to dilution", "Suitable for cleaning in conformity to UNI 11493:2016-1"],
    packaging: "1 L boxes of 12 - 5 L boxes of 4",
    coverage: [["Terracotta", "1:5", "10-20 m2 per litre"], ["Porcelain tiles", "1:5 to 1:10", "40-80 m2 per litre"], ["Natural stone", "1:5 to 1:10", "20-35 m2 per litre"]],
    page: 7, hasScene: true, beforeAfter: true,
  },
  {
    name: "INSTANT REMOVER", slug: "instant-remover", category: "cleaners", line: "professional",
    title: "Instant cleaner for fresh cement grout",
    badges: ["Biodegradable ingredients", "Patent pending"],
    surfaces: ["Porcelain tiles", "Ceramic tiles", "Glass mosaic", "Quarry tiles"],
    whatFor: ["Removes fresh cement grout residue, including grouts containing additives", "Ideal for cleaning the backs of large format tile before laying, and grout floats and tools", "Prevents dull smears caused by unremoved grout residue"],
    advantages: ["Rapid Dry Technology - fast acting, used during the laying process", "Does not foam and needs no rinsing", "Safe for the installer and the environment", "Does not damage materials, grout, or aluminium and steel trims", "High coverage; indoor and outdoor, walls and floors", "Patented application system with certified results"],
    packaging: "750 ml spray bottles, boxes of 12",
    coverage: [["Large format tile", "spray", "up to 350 linear metres per bottle"], ["Mosaic", "spray", "up to 15 m2 per bottle"]],
    page: 8, hasScene: true,
  },
  {
    name: "MAX", slug: "max", category: "cleaners", line: "professional",
    title: "Solvent-based wax remover",
    badges: ["Biodegradable ingredients"],
    surfaces: ["Terracotta", "Quarry tiles", "Porcelain tiles", "Unpolished stone and agglomerates", "Glazed ceramic tiles", "Concrete"],
    whatFor: ["Removes seasoned treatments or treatments of unknown origin", "A strong wax remover where traditional water-based removers fail", "Highly recommended for stubborn wax treatments on terracotta and stone"],
    advantages: ["Can be used with a single-disc machine - no flammability risk", "Excellent as an intensive degreaser on ingrained dirt"],
    packaging: "5 L cans, boxes of 4",
    coverage: [["Wax removal", "1:5", "20 m2 per litre"]],
    page: 9, hasScene: true, beforeAfter: true,
  },
  {
    name: "NORUST", slug: "norust", category: "cleaners", line: "professional",
    title: "Rust stain remover",
    badges: [],
    surfaces: ["Marble", "Granite", "Natural stone", "Agglomerates", "Porcelain tiles", "Ceramic tiles", "Terracotta", "Concrete"],
    whatFor: ["Removes surface rust stains", "Its non-acidic formulation suits delicate applications such as polished marble"],
    advantages: ["Viscous consistency acts directly on the stain - no wastage", "Removes stains in just 15 minutes"],
    packaging: "75 ml bottles, boxes of 12",
    coverage: [["Rust spots", "undiluted", "spot application"]],
    page: 10, hasScene: false,
  },
  {
    name: "NOSPOT", slug: "nospot", category: "cleaners", line: "professional",
    title: "Spray stain-remover for terracotta, quarry tiles and natural stone",
    badges: [],
    surfaces: ["Terracotta", "Quarry tiles", "Marble, granite and natural stone", "Agglomerates", "Concrete"],
    whatFor: ["Removes greasy and oily stains from terracotta, quarry tiles, natural stone, granite, agglomerates, tumbled marble, cobblestones and concrete"],
    advantages: ["Extremely practical easy-to-use spray", "Very effective on external terracotta, untreated or treated with non-filming products", "Leaves no traces when the stain is fresh", "Cleans where normal stain-removers do not reach", "Performs even on untreated surfaces"],
    packaging: "200 ml cans, boxes of 12",
    coverage: [["Oil and grease spots", "spray", "spot application"]],
    page: 11, hasScene: true, beforeAfter: true,
  },
  {
    name: "PHZERO", slug: "phzero", category: "cleaners", line: "professional",
    title: "Strong acid descaler",
    badges: ["Biodegradable ingredients"],
    surfaces: ["Terracotta", "Quarry tiles", "Porcelain tiles"],
    whatFor: ["Removes dirt and building-site residues", "Eliminates saline efflorescence; cleanses and removes deposits", "Essential for terracotta when normal buffered acids are not effective"],
    advantages: ["Buffered acid without hydrochloric acid - no harmful fumes", "Longer working time than pure acids with their instant, short reaction", "Viscosity makes it ideal on vertical surfaces", "Removes deposits and cleans in one pass thanks to added surfactants"],
    packaging: "5 L boxes of 4",
    coverage: [["Terracotta", "1:5", "20 m2 per litre"], ["Porcelain tiles", "1:5", "40 m2 per litre"]],
    page: 12, hasScene: true,
  },
  {
    name: "PS87 PRO", slug: "ps87-pro", category: "cleaners", line: "professional",
    title: "Professional degreasing cleaning agent",
    badges: ["Biodegradable ingredients"],
    surfaces: ["Porcelain tiles", "Unpolished stone and agglomerates", "Glazed ceramic tiles", "Concrete", "Linoleum and PVC", "Terracotta", "Quarry tiles"],
    whatFor: ["Diluted: cleans and degreases dirty floors in porcelain, ceramic, natural stone, terracotta and concrete", "Undiluted: removes stubborn stains from porcelain floor tiles", "Excellent for basic cleaning of acid-sensitive natural stone and concrete", "Wax-remover for water-based, metallic and re-polishable waxes", "Eliminates pre-treatment residues from polished porcelain"],
    advantages: ["A 3-in-one product: cleaner, stain-remover, wax-remover", "The only one that can eliminate stubborn stains from porcelain tiles", "It cleans but does not attack", "Extremely easy to use"],
    packaging: "1 L boxes of 12 - 5 L boxes of 4",
    coverage: [["Maintenance", "1:20", "200 m2 per litre"], ["Dewaxing", "1:5", "20 m2 per litre"], ["Initial stone wash", "1:5", "30 m2 per litre"]],
    page: 13, hasScene: true, beforeAfter: true, quote: "Cleaner, stain-remover, wax-remover. Three in one.",
  },
  {
    name: "SR95", slug: "sr95", category: "cleaners", line: "professional",
    title: "Stain-remover",
    badges: [],
    surfaces: ["Porcelain tiles", "Stone and agglomerates", "Glazed ceramic tiles", "Concrete"],
    whatFor: ["Removes coloured organic stains: wine, coffee, soft drinks, tea, indelible marker"],
    advantages: ["Removes ingrained stains where normal cleaners have no effect", "Developed for natural stone - marble, travertine, agglomerates", "Safe on polished natural stone: does not attack the finish", "Ideal for low-absorption ceramic surfaces"],
    packaging: "75 ml bottles, boxes of 12",
    coverage: [["Coloured stains", "undiluted", "spot application"]],
    page: 14, hasScene: true,
  },
  {
    name: "ZEROSIL", slug: "zerosil", category: "cleaners", line: "professional",
    title: "Silicone remover",
    badges: [],
    surfaces: ["Porcelain tiles", "Ceramic tiles", "Marble", "Glass", "Metal"],
    whatFor: ["Removes silicone, glue, adhesive tape, old labels and polyurethane foam residues", "Also effective on candle wax, resin, tar, bitumen and greasy surface stains", "Quick to apply with the included spatula"],
    advantages: ["Usable on marble, stone and grout joints to remove surface residues", "Viscous consistency acts directly on the residue - no wastage", "Dissolves hardened silicone in 20 minutes", "Pleasant citrus fragrance"],
    packaging: "250 ml can, boxes of 12",
    coverage: [["Silicone and residues", "undiluted", "spot application"]],
    page: 15, hasScene: true,
  },
  {
    name: "CONCRETE SHIELD", slug: "concrete-shield", category: "protectors", line: "professional",
    title: "Colour-enhancing stain-proof sealer for concrete",
    badges: ["Water-based technology"],
    surfaces: ["Concrete", "Stamped concrete", "Interlocking pavers", "Marble chip cement tile"],
    whatFor: ["Enhances indoor and outdoor concrete and protects it against stains and water", "Creates a barrier that lets oil and grease be removed before they penetrate", "Makes outdoor pavers, marble-chip tiles and stamped concrete weather resistant", "Strengthens industrial floors and makes them dust resistant; residential floors can be finished with wax"],
    advantages: ["No hydrocarbon solvents - eco-friendly", "Reversible treatment", "Consolidating and dust-resistant action", "UV resistant (ASTM G154)", "Water-based: unaffected by residual moisture, drastically reducing site time", "A+ classified under the French VOC regulation"],
    packaging: "5 L boxes of 4",
    coverage: [["Concrete", "as applied", "10-15 m2 per litre"]],
    page: 16, hasScene: true,
  },
  {
    name: "CONCRETE HYDRO", slug: "concrete-hydro", category: "protectors", line: "professional",
    title: "Consolidating water repellent for concrete",
    badges: ["Water-based technology", "Indoor Air Comfort Gold"],
    surfaces: ["Concrete", "Plaster", "Brick", "Tuff"],
    whatFor: ["Protects surfaces from weathering, strengthening them and preventing chalking", "Prevents water absorption while keeping the surface breathable", "Prevents efflorescence build-up - carbonates, sulphates, saltpetre", "Limits algae, mould and lichen growth; counters smog blackening"],
    advantages: ["Breathable dust-resistant action without a surface film", "Does not alter the finish; UV-resistant and non-yellowing", "Ready to use; treated concrete and plaster can be painted", "VOC-free with the Indoor Air Comfort Gold certificate - meets LEED, BREEAM and WELL criteria"],
    packaging: "5 L boxes of 4",
    coverage: [["Concrete, plaster, brick, tuff", "ready to use", "up to 8 m2 per litre"]],
    page: 17, hasScene: true,
  },
  {
    name: "CONTRACTOR'S CHOICE", slug: "contractors-choice", category: "protectors", line: "professional",
    title: "Stone and grout sealer",
    badges: ["Water-based technology"],
    surfaces: ["Natural stone", "Cement grout joints", "Concrete", "Terracotta"],
    whatFor: ["Protects natural stone and grout joints from stains", "Protects grout joints from water and humidity", "Makes cleaning fast and easy; keeps grout looking new for years", "Indoors and outdoors"],
    advantages: ["Water-based and eco-friendly", "Dual action: protects grout and eases cleaning", "Does not alter grout colour; odourless; fast drying", "VOC free - contributes towards LEED credits", "PFOA free"],
    packaging: "3.78 L (1 US gal), boxes of 4",
    coverage: [["Natural stone", "as applied", "33 m2 per litre"], ["Cement grout joints", "as applied", "90-185 m2 per litre"]],
    page: 18, hasScene: true, beforeAfter: true,
  },
  {
    name: "FOB XTREME", slug: "fob-xtreme", category: "protectors", line: "professional",
    title: "Extreme water- and oil-repellent protection",
    badges: ["Advanced Solvent Technology"],
    surfaces: ["Natural stone and agglomerates", "Marble and granite", "Concrete", "Tuff", "WPC", "Terracotta", "Quarry tiles"],
    whatFor: ["Hampers the absorption of common watery and oily stains", "Protective base coat before waxing rustic or textured interior surfaces", "Excellent for grit and coloured cement tiles", "Natural-finish breathing protection"],
    advantages: ["Does not alter original colour or form a surface film", "Does not alter terracotta frost resistance", "Excellent on rustic ground terracotta and tumbled marble", "Ideal near kitchens, barbecues and car driveways", "Treated surfaces are safe for food contact", "A+ classified under the French VOC regulation"],
    packaging: "1 L boxes of 6 - 5 L boxes of 4",
    coverage: [["Stone", "as applied", "10-30 m2 per litre"], ["Terracotta, rustic Tuscan or polished", "as applied", "15-20 m2 per litre"], ["Terracotta, handmade", "as applied", "up to 10 m2 per litre"]],
    page: 19, hasScene: true,
  },
  {
    name: "HYDROREP", slug: "hydrorep", category: "protectors", line: "professional",
    title: "Water-repellent protection",
    badges: ["Solvent Technology"],
    surfaces: ["Unpolished marble and granite", "Unpolished stone and agglomerates", "Concrete", "Manufactured stone"],
    whatFor: ["Protects outdoor floors from water and damp", "Makes walls and coverings water-repellent", "Ideal for concrete; protects grout joints", "Protects against weathering deterioration"],
    advantages: ["Breathable, lasting, renewable protection", "Does not affect the material's natural look; never yellows", "High penetration depth and high coverage", "Prevents moss and mould; protects against efflorescence", "A+ classified under the French VOC regulation"],
    packaging: "1 L boxes of 12 - 5 L boxes of 4",
    coverage: [["Natural stone", "as applied", "10-20 m2 per litre"], ["Concrete", "as applied", "5 m2 per litre"]],
    page: 20, hasScene: true,
  },
  {
    name: "HYDROREP ECO", slug: "hydrorep-eco", category: "protectors", line: "professional",
    title: "Eco-compatible water-repellent protection",
    badges: ["Water-based technology"],
    surfaces: ["Unpolished stone and agglomerates", "Concrete", "Terracotta", "Exposed bricks", "Quarry tiles", "Plaster", "Tuff"],
    whatFor: ["Water-repellent with natural finish - penetrates deeply while the surface breathes", "Hampers algae, mould and lichen build-up", "Protects against weathering deterioration"],
    advantages: ["Anti-fouling barrier certified to UNI EN ISO 846:1999", "Ideal for exterior walls; resists UV", "Does not alter terracotta frost resistance; protects against efflorescence", "Applies to surfaces with residual moisture - drastically reduced times", "Preserves breathability above 90%", "A+ classified under the French VOC regulation"],
    packaging: "1 L boxes of 12 - 5 L boxes of 4",
    coverage: [["Terracotta, brick, quarry tiles, stone, plaster", "as applied", "10-20 m2 per litre"], ["Concrete", "as applied", "8-10 m2 per litre"]],
    page: 21, hasScene: true, beforeAfter: true,
  },
  {
    name: "MP90", slug: "mp90", category: "protectors", line: "professional",
    title: "Water- and oil-repellent protection",
    badges: ["Solvent Technology"],
    surfaces: ["Polished porcelain tiles", "Marble and granite", "Stone and agglomerates"],
    whatFor: ["The best stain-proofing product for porcelain tiles, marble and granite", "Anti-graffiti treatment for vertical natural stone", "Ideally suited to kitchen and bathroom tops", "Hampers absorption of watery and oily stains"],
    advantages: ["Does not change the natural colour of surfaces or form a film", "Treated surfaces are safe for food contact", "Impregnates, protects and makes cleaning easier", "Ideal for crackle glazed tiles", "A+ classified under the French VOC regulation"],
    packaging: "1 L boxes of 6 - 5 L boxes of 4",
    coverage: [["Marble / granite", "as applied", "30 m2 per litre"], ["Porcelain", "as applied", "30-40 m2 per litre"], ["Venetian terrazzo", "as applied", "30 m2 per litre"]],
    page: 22, hasScene: true,
  },
  {
    name: "MP90 ECO XTREME", slug: "mp90-eco-xtreme", category: "protectors", line: "professional",
    title: "Extreme eco-compatible water- and oil-repellent protection",
    badges: ["Ultimate Shield", "Indoor Air Comfort Gold"],
    surfaces: ["Polished porcelain tiles", "Marble and granite", "Natural stone and agglomerates", "Concrete"],
    whatFor: ["The best environmentally-friendly stain protection for porcelain, natural stone, marble and granite in polished, brushed and matt smoothed finishes", "Reduces absorption without changing the material's look", "Ideal for grout joints, crackle surfaces, grit, resin-marble, stone slabs, coloured cement tiles and manufactured stone", "Anti-graffiti protection: paint cannot bond and cleans off fast"],
    advantages: ["Extremely low VOC with the Indoor Air Comfort Gold certificate", "Free of hydrocarbon solvents", "Water-based: withstands residual humidity, applies 24-48 hours after the initial wash", "Single-coat application, rubbed gently until absorbed", "No surface film, no yellowing", "Walk-on after just 2 hours", "Application conditions as printed: temperature = 20 C (approximately 20 C), humidity at or below 60%"],
    packaging: "1 L boxes of 6 - 5 L boxes of 4",
    coverage: [["Polished porcelain tiles", "as applied", "30-50 m2 per litre"], ["Polished marble / granite", "as applied", "20-30 m2 per litre"], ["Matte polished stone", "as applied", "10-20 m2 per litre"]],
    page: 23, hasScene: true, beforeAfter: true, quote: "The best eco stain protection for polished stone.",
  },
  {
    name: "PW10", slug: "pw10", category: "protectors", line: "professional",
    title: "Eco-compatible pre-laying treatment against efflorescence",
    badges: ["Water-based technology", "Indoor Air Comfort Gold"],
    surfaces: ["Back of natural stone surfaces", "Granite", "Marble", "Agglomerates", "Terracotta and absorbent materials"],
    whatFor: ["Efflorescence-blocking sealant applied before laying to the back of tiles and absorbent slabs", "Stops salts, tannin and oxides rising from the substrate - prevents streaks and stains", "Water-repellent and consolidating properties"],
    advantages: ["No surface film; treated materials keep breathing", "Does not essentially alter glue adhesion (UNI EN 1348-2009, ASTM C482-02 R-2009)", "Applied after laying, prevents blackening from smog, carbonatation, sulphation and biodeterioration", "VOC-free with the Indoor Air Comfort Gold certificate"],
    packaging: "5 L boxes of 4 - 100 L",
    coverage: [["Back of slabs", "as applied", "10-15 m2 per litre"]],
    page: 24, hasScene: true, beforeAfter: true,
  },
  {
    name: "STONEPLUS", slug: "stoneplus", category: "protectors", line: "professional",
    title: "Water- and oil-repellent protective agent with reviving effect",
    badges: ["Solvent Technology"],
    surfaces: ["Stone and agglomerates", "Marble", "Granite"],
    whatFor: ["Protects and revives the original colour of polished, untreated and tumbled natural stone", "Deeply penetrates and protects from watery or oily stains", "Ideal for worktops, rosettes and decorative stone objects, indoors and out"],
    advantages: ["Reviving effect on all finishes", "Does not yellow, resists UV, enduring protection", "Extremely high coverage", "Eliminates minute granite excoriations", "No surface film; food-contact safe", "A+ classified under the French VOC regulation"],
    packaging: "1 L boxes of 6 - 5 L boxes of 4",
    coverage: [["Polished stone", "as applied", "30-50 m2 per litre"], ["Untreated stone", "as applied", "15-25 m2 per litre"]],
    page: 25, hasScene: true, beforeAfter: true,
  },
  {
    name: "STONEPLUS ECO", slug: "stoneplus-eco", category: "protectors", line: "professional",
    title: "Colour-enhancing protective agent",
    badges: ["Water-based technology"],
    surfaces: ["Natural stone", "Marble", "Granite"],
    whatFor: ["Colour-reviving protector for polished, untreated and tumbled natural stone", "Penetrates deep and reduces dirt absorption"],
    advantages: ["Reviving effect on all finishes", "Extremely low VOC - helps gain LEED credits", "Water-based: withstands residual humidity, applies a few days after the initial wash", "Revives grouting too; never yellows or films; UV-stable", "Food-contact safe", "A+ classified under the French VOC regulation"],
    packaging: "1 L boxes of 6 - 5 L boxes of 4",
    coverage: [["Polished stone", "as applied", "30-50 m2 per litre"], ["Untreated stone", "as applied", "15-25 m2 per litre"]],
    page: 26, hasScene: true, beforeAfter: true,
  },
  {
    name: "STOP DIRT", slug: "stop-dirt", category: "protectors", line: "professional",
    title: "Dirt repellent",
    badges: ["Solvent Technology"],
    surfaces: ["Textured porcelain tiles", "Unpolished porcelain tiles", "Lappato porcelain tiles"],
    whatFor: ["Makes cleaning quick and easy and surfaces hygienic", "Improves resistance to dirt", "Maintains the original appearance over time"],
    advantages: ["Prolonged protection, interior and exterior", "High coverage", "Does not alter slip resistance (B.C.R.A. and ASTM C1028-2007 tested)", "No surface film; UV resistant, non-yellowing", "A+ classified under the French VOC regulation"],
    packaging: "500 ml boxes of 12",
    coverage: [["Textured, natural and lappato porcelain", "as applied", "up to 70 m2 per litre"]],
    page: 27, hasScene: true, beforeAfter: true,
  },
  {
    name: "W68", slug: "w68", category: "protectors", line: "professional",
    title: "Stain protector for unpolished surfaces",
    badges: ["Water-based technology", "Indoor Air Comfort Gold"],
    surfaces: ["Unpolished stone and agglomerates", "Terracotta", "Quarry tiles", "Concrete"],
    whatFor: ["Seals and protects porous materials - untreated stone, terracotta, concrete - from oily dirt", "Hampers absorption of watery and oily stains, interior and exterior", "Protective base coat before wax on interior floors", "Anti-graffiti protection that stops paint bonding"],
    advantages: ["Natural finish - the surface's appearance does not change", "Water-based, free of hydrocarbon solvents; applies onto residual moisture", "No surface film; terracotta frost resistance unaffected", "Excellent on concrete; food-contact safe", "VOC-free with the Indoor Air Comfort Gold certificate"],
    packaging: "1 L boxes of 12 - 5 L boxes of 4",
    coverage: [["Terracotta, rustic Tuscan or polished", "as applied", "15-20 m2 per litre"], ["Concrete and handmade terracotta", "as applied", "7-10 m2 per litre"], ["Stone", "as applied", "10-20 m2 per litre"]],
    page: 28, hasScene: true, beforeAfter: true,
  },
  {
    name: "WET ECO", slug: "wet-eco", category: "protectors", line: "professional",
    title: "Wet-look colour enhancing protector",
    badges: ["Water-based technology", "Indoor Air Comfort Gold"],
    surfaces: ["Unpolished natural stones", "Unpolished agglomerates", "Terracotta"],
    whatFor: ["Stain-proof, anti-dirt sealer with wet effect for unpolished stone, agglomerates and terracotta", "Prevents stain absorption and eases dirt removal", "Particularly suited to exteriors; prevents flaking"],
    advantages: ["Water-based eco-friendly treatment", "High resistance to heavy traffic and weathering", "Does not peel or yellow; eases later maintenance", "Terracotta frost resistance unaffected (UNI EN ISO 10545-12)", "Plant-based: organic and renewable raw materials", "VOC-free with the Indoor Air Comfort Gold certificate"],
    packaging: "1 L boxes of 12 - 5 L boxes of 4",
    coverage: [["Unpolished stones and agglomerates", "as applied", "10-20 m2 per litre"], ["Terracotta", "as applied", "7-20 m2 per litre"]],
    page: 29, hasScene: true, beforeAfter: true,
  },
  {
    name: "CLASSIC", slug: "classic", category: "finishing", line: "professional",
    title: "Eco-friendly liquid wax",
    badges: [],
    surfaces: ["Marble", "Venetian terrazzo", "Grit", "Natural stone", "Terracotta", "Cement tiles"],
    whatFor: ["Protects floors in marble, travertine and stone agglomerates including grit and terrazzo", "Revitalises the shine of polished finishes", "Ideal first and final coat for traditional terracotta treatment and routine maintenance"],
    advantages: ["A splendid natural sheen", "Easy to apply and maintain", "Protects surfaces from the effects of time", "Does not degenerate with maintenance; can be re-polished"],
    packaging: "1 L boxes of 12 - 5 L boxes of 4",
    coverage: [["Terracotta", "as applied", "30 m2 per litre"], ["Stone", "as applied", "30-40 m2 per litre"]],
    page: 30, indoorOnly: true, hasScene: true,
  },
  {
    name: "LONGLIFE", slug: "longlife", category: "finishing", line: "professional",
    title: "Glossy protective wax",
    badges: [],
    surfaces: ["Terracotta", "Quarry tiles", "Slate", "Stone and agglomerates", "Rubber and PVC", "Plastic laminates", "Linoleum", "Resin", "Vinyl"],
    whatFor: ["Protects high-traffic floors", "Perfect for rubber, PVC, vinyl, laminates, linoleum and resin", "Ideal for unpolished natural stone, granite and terracotta", "Maintains quartz concrete floors treated with BETON", "Generates a high-sheen, ultra-protective polymer surface film", "Protects polished natural stone floors in public areas"],
    advantages: ["No need to polish", "High adhesion strength; easy to apply", "Undiluted or diluted as necessary", "Maintainable with a high-speed single-disc machine"],
    packaging: "1 L boxes of 12",
    coverage: [["Terracotta", "as applied", "30 m2 per litre"], ["Stone", "as applied", "30-40 m2 per litre"], ["Rubber, PVC, laminates, linoleum, resin", "undiluted", "30 m2 per litre"]],
    page: 31, indoorOnly: true, hasScene: true,
  },
  {
    name: "CLEAN&SHINE", slug: "clean-and-shine", category: "ready-to-use", line: "ready-to-use",
    title: "Sparkling cleanliness in the home",
    badges: ["Biodegradable ingredients"],
    surfaces: ["Porcelain tiles", "Glazed ceramic tiles", "Stone", "Glass and mirrors", "Leather", "Plastic laminates and rubber", "Steel", "Marble and granite", "Quartz and agglomerates"],
    whatFor: ["Cleans all surfaces: wall tiles, ceramic, laminates, glazed surfaces, stainless steel, glass and mirrors", "Ideal for kitchen and bathroom cabinet doors, office furniture and laminates", "Ideal for marble, granite and quartz agglomerate tops"],
    advantages: ["Delicate detergent for all surfaces", "No rinsing; quick drying; does not smear", "HACCP-compliant; no alcohol or ammonia", "Delicate formula with degreasing action", "Pet safe"],
    packaging: "750 ml spray bottles, boxes of 6",
    coverage: [["All surfaces", "spray", "ready to use"]],
    page: 32, hasScene: true,
  },
  {
    name: "DEEPCLEAN", slug: "deepclean", category: "ready-to-use", line: "ready-to-use",
    title: "Descaling cleaning agent",
    badges: ["Biodegradable ingredients"],
    surfaces: ["Porcelain tiles", "Ceramic tiles", "Mosaics", "Glass", "Taps and chrome-plated elements"],
    whatFor: ["Removes limescale effectively without traces or dull marks", "Thoroughly cleans all bathroom surfaces"],
    advantages: ["From sanitary fittings to coverings, one product", "Active foam formula - does not drip", "Ideal for mosaics and taps; safe on methacrylate tubs and stainless fittings", "Cleans and deodorises with white musk and mint"],
    packaging: "750 ml spray bottles, boxes of 6",
    coverage: [["Bathroom surfaces", "spray", "ready to use"]],
    page: 33, hasScene: true,
  },
  {
    name: "FUGANET", slug: "fuganet", category: "ready-to-use", line: "ready-to-use",
    title: "Specific cleaning for grouting",
    badges: ["Biodegradable ingredients"],
    surfaces: ["All types of grouting"],
    whatFor: ["Thoroughly cleans grouts in ceramic tile floors and walls", "Suitable for single-fired and double-fired porcelain; unsuitable only for porous surfaces treated with wax"],
    advantages: ["Practical ergonomic spray packaging", "Does not damage or corrode wall tiles", "No acids or sodium hypochlorite"],
    packaging: "750 ml spray bottles, boxes of 6",
    coverage: [["Grout lines", "spray", "up to 850 linear metres per bottle"]],
    page: 34, hasScene: true, beforeAfter: true,
  },
  {
    name: "MARBLE REFRESH", slug: "marble-refresh", category: "ready-to-use", line: "ready-to-use",
    title: "Polishes and renews marble worktops",
    badges: ["Biodegradable ingredients"],
    surfaces: ["Marble", "Granite", "Natural stone", "Marble-resin and quartz-resin agglomerates", "Quartz"],
    whatFor: ["Cleans all natural stone surfaces treated with waterproofing products", "Renews and maintains stain-proofing protection over time", "Perfect for marble, quartz and granite worktops; also for previously waterproofed absorbent ceramic tops"],
    advantages: ["Daily use cleans and reinforces the protection treatment", "pH neutral - ideal for the most delicate natural stone", "No rinsing; quick drying; pleasant fragrance", "Food-contact safe", "A+ classified under the French VOC regulation"],
    packaging: "750 ml spray bottles, boxes of 6",
    coverage: [["Worktops", "spray", "ready to use"]],
    page: 35, hasScene: false,
  },
  {
    name: "NODROPS", slug: "nodrops", category: "ready-to-use", line: "ready-to-use",
    title: "Water-mark protection",
    badges: ["Biodegradable ingredients"],
    surfaces: ["Shower cubicles", "Glass", "Glass mosaic", "Glazed ceramic tiles", "Mirrors"],
    whatFor: ["Cleans and protects glass, making it hydrophilic - water runs off without limescale residues", "Ideal for shower cubicles"],
    advantages: ["Easy to apply, no rinsing, no smears", "Also for taps, steel and plexiglass maintenance", "Acid-free formula, safe near acid-sensitive materials", "Used regularly, no other limescale removers are needed"],
    packaging: "750 ml spray bottles, boxes of 6",
    coverage: [["Glass and shower cubicles", "spray", "ready to use"]],
    page: 36, hasScene: true, beforeAfter: true,
  },
  {
    name: "RAPIDSAN", slug: "rapidsan", category: "ready-to-use", line: "ready-to-use",
    title: "Eco disinfectant",
    badges: ["Biodegradable ingredients"],
    surfaces: ["All surfaces"],
    whatFor: ["3-in-1: cleans, disinfects and eliminates odours", "Daily disinfection of surfaces and frequently touched objects", "Ideal for kitchens, bathrooms, offices, schools, clinics, hotels and hospitals", "Perfect for marble, granite and quartz agglomerate countertops"],
    advantages: ["Eco sanitising formula effective against germs and bacteria", "Contains tea tree oil", "No chemical residue that could damage surfaces", "Odour control formula; pet safe", "No rinsing, quick drying, safe on delicate surfaces", "Degreasing action; HACCP-compliant"],
    packaging: "750 ml spray bottles, boxes of 6",
    coverage: [["All surfaces", "spray", "ready to use"]],
    page: 37, hasScene: true,
  },
  {
    name: "FUGAPROOF", slug: "fugaproof", category: "ready-to-use", line: "ready-to-use",
    title: "Grout protection",
    badges: ["Water-based technology"],
    surfaces: ["All types of grouting"],
    whatFor: ["Protects and sanitises cement-based grouts", "Facilitates dirt removal and routine cleaning", "Prevents water and stains being absorbed"],
    advantages: ["Water-based and ready to use", "Safe with a spray applicator", "VOC-free, EC1Plus-classified", "Does not alter grout colour; odourless", "Applies to surfaces with residual moisture", "A+ classified under the French VOC regulation"],
    packaging: "750 ml spray bottles, boxes of 6",
    coverage: [["Grout lines", "spray", "up to 850 linear metres per bottle"]],
    page: 38, hasScene: true, beforeAfter: true,
  },
];

export const filaProductBySlug = new Map(filaProducts.map((p) => [p.slug, p]));

export function filaProductsByCategory(category: FilaCategory) {
  return filaProducts.filter((p) => p.category === category);
}
