/**
 * KalingaStone Quartz - complete 69-shade range, extracted from the
 * manufacturer's 2023 catalogue (see docs in the owner's brief). NEVER
 * invent, extend or "correct" shade names - Wizzard, Bianco Gioa,
 * Bermingham, Nisley, Ush, Repen, Grey Fjordo and Chandan are the brand's
 * own spellings. Series = price/design tier (7 premium veined → 1 simplest
 * particulate); family = editorial colour facet for filtering.
 */
export type QuartzShade = {
  name: string;
  slug: string;
  /** Tier: "7" premium veined … "1" simplest. "1 A" is the catalogue's own oddity. */
  series: string;
  /** Slab size, mm */
  size: string;
  isNew: boolean;
  microban: boolean;
  family: "white" | "veined" | "beige" | "grey" | "dark";
  hasLifestyle: boolean;
};

export const quartzShades: QuartzShade[] = [
  {
    name: "New Bianco Alaska",
    slug: "new-bianco-alaska",
    series: "7",
    size: "3150 × 1450 × 20",
    isNew: true,
    microban: false,
    family: "white",
    hasLifestyle: true,
  },
  {
    name: "Bianco Venatino",
    slug: "bianco-venatino",
    series: "7",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "white",
    hasLifestyle: true,
  },
  {
    name: "Calacatta Imperial",
    slug: "calacatta-imperial",
    series: "7",
    size: "3150 × 1450 × 20",
    isNew: true,
    microban: false,
    family: "veined",
    hasLifestyle: true,
  },
  {
    name: "Crystal Bliss",
    slug: "crystal-bliss",
    series: "7",
    size: "3250 × 1650 × 20",
    isNew: false,
    microban: false,
    family: "white",
    hasLifestyle: true,
  },
  {
    name: "Crystal Serene",
    slug: "crystal-serene",
    series: "7",
    size: "3250 × 1650 × 20",
    isNew: false,
    microban: false,
    family: "white",
    hasLifestyle: true,
  },
  {
    name: "Calacatta Lazza",
    slug: "calacatta-lazza",
    series: "7",
    size: "3250 × 1650 × 20",
    isNew: false,
    microban: false,
    family: "veined",
    hasLifestyle: true,
  },
  {
    name: "Alluring",
    slug: "alluring",
    series: "7",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "veined",
    hasLifestyle: true,
  },
  {
    name: "Pietra Grey",
    slug: "pietra-grey",
    series: "6",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "grey",
    hasLifestyle: true,
  },
  {
    name: "Calacatta Rivolo",
    slug: "calacatta-rivolo",
    series: "6",
    size: "3250 × 1650 × 20",
    isNew: false,
    microban: false,
    family: "veined",
    hasLifestyle: true,
  },
  {
    name: "Calacatta Pristine",
    slug: "calacatta-pristine",
    series: "6",
    size: "3250 × 1650 × 20",
    isNew: false,
    microban: false,
    family: "white",
    hasLifestyle: true,
  },
  {
    name: "Calacatta Nero",
    slug: "calacatta-nero",
    series: "6",
    size: "3250 × 1650 × 20",
    isNew: false,
    microban: false,
    family: "veined",
    hasLifestyle: true,
  },
  {
    name: "Bianco River",
    slug: "bianco-river",
    series: "6",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "white",
    hasLifestyle: true,
  },
  {
    name: "Tundra",
    slug: "tundra",
    series: "6",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "grey",
    hasLifestyle: true,
  },
  {
    name: "Wizzard",
    slug: "wizzard",
    series: "6",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "dark",
    hasLifestyle: true,
  },
  {
    name: "Calacatta Venezia",
    slug: "calacatta-venezia",
    series: "5",
    size: "3250 × 1650 × 20",
    isNew: false,
    microban: false,
    family: "veined",
    hasLifestyle: true,
  },
  {
    name: "Bermingham",
    slug: "bermingham",
    series: "5",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "beige",
    hasLifestyle: true,
  },
  {
    name: "Bianco Gioa",
    slug: "bianco-gioa",
    series: "5",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "white",
    hasLifestyle: true,
  },
  {
    name: "Bianco Superiore",
    slug: "bianco-superiore",
    series: "5",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "white",
    hasLifestyle: true,
  },
  {
    name: "Nisley",
    slug: "nisley",
    series: "5",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "beige",
    hasLifestyle: true,
  },
  {
    name: "Crema Gold",
    slug: "crema-gold",
    series: "5",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "beige",
    hasLifestyle: true,
  },
  {
    name: "New Extra White",
    slug: "new-extra-white",
    series: "5",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "white",
    hasLifestyle: true,
  },
  {
    name: "Classic Pearl",
    slug: "classic-pearl",
    series: "5",
    size: "3150 × 1450 × 20",
    isNew: true,
    microban: false,
    family: "veined",
    hasLifestyle: true,
  },
  {
    name: "Bianco Oro",
    slug: "bianco-oro",
    series: "4",
    size: "3150 × 1450 × 20",
    isNew: true,
    microban: false,
    family: "veined",
    hasLifestyle: true,
  },
  {
    name: "Bianco Carrara",
    slug: "bianco-carrara",
    series: "4",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: true,
    family: "veined",
    hasLifestyle: true,
  },
  {
    name: "Carrara Marmi",
    slug: "carrara-marmi",
    series: "4",
    size: "3300 × 2000 × 20",
    isNew: true,
    microban: false,
    family: "veined",
    hasLifestyle: true,
  },
  {
    name: "Noah",
    slug: "noah",
    series: "4",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "beige",
    hasLifestyle: true,
  },
  {
    name: "Crema Venato Extra",
    slug: "crema-venato-extra",
    series: "4",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "veined",
    hasLifestyle: true,
  },
  {
    name: "Grey Fjordo",
    slug: "grey-fjordo",
    series: "4",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "grey",
    hasLifestyle: true,
  },
  {
    name: "Manhattan Grey",
    slug: "manhattan-grey",
    series: "4",
    size: "3250 × 1650 × 20",
    isNew: true,
    microban: false,
    family: "dark",
    hasLifestyle: true,
  },
  {
    name: "Grigio Oro",
    slug: "grigio-oro",
    series: "4",
    size: "3150 × 1450 × 20",
    isNew: true,
    microban: false,
    family: "grey",
    hasLifestyle: false,
  },
  {
    name: "Gris Venato",
    slug: "gris-venato",
    series: "4",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "grey",
    hasLifestyle: false,
  },
  {
    name: "Bianco Classic",
    slug: "bianco-classic",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: true,
    family: "white",
    hasLifestyle: true,
  },
  {
    name: "Stellar White",
    slug: "stellar-white",
    series: "3",
    size: "3250 × 1650 × 20",
    isNew: true,
    microban: false,
    family: "white",
    hasLifestyle: false,
  },
  {
    name: "Peppercorn White",
    slug: "peppercorn-white",
    series: "3",
    size: "3250 × 1650 × 20",
    isNew: false,
    microban: false,
    family: "white",
    hasLifestyle: false,
  },
  {
    name: "Vetro Bianco",
    slug: "vetro-bianco",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "white",
    hasLifestyle: true,
  },
  {
    name: "Torres",
    slug: "torres",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: true,
    microban: false,
    family: "beige",
    hasLifestyle: false,
  },
  {
    name: "Repen",
    slug: "repen",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: true,
    family: "beige",
    hasLifestyle: false,
  },
  {
    name: "Classic Beige",
    slug: "classic-beige",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: true,
    family: "beige",
    hasLifestyle: true,
  },
  {
    name: "Toasted Almond",
    slug: "toasted-almond",
    series: "3",
    size: "3250 × 1650 × 20",
    isNew: true,
    microban: false,
    family: "beige",
    hasLifestyle: false,
  },
  {
    name: "Stellar Grey",
    slug: "stellar-grey",
    series: "3",
    size: "3250 × 1650 × 20",
    isNew: true,
    microban: false,
    family: "grey",
    hasLifestyle: false,
  },
  {
    name: "Cosmopolitan",
    slug: "cosmopolitan",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: true,
    microban: false,
    family: "beige",
    hasLifestyle: true,
  },
  {
    name: "Cement",
    slug: "cement",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "grey",
    hasLifestyle: false,
  },
  {
    name: "Chandan",
    slug: "chandan",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: true,
    family: "grey",
    hasLifestyle: false,
  },
  {
    name: "Grigio Londra",
    slug: "grigio-londra",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "grey",
    hasLifestyle: true,
  },
  {
    name: "Concrete",
    slug: "concrete",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "grey",
    hasLifestyle: false,
  },
  {
    name: "Ash Grey",
    slug: "ash-grey",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "grey",
    hasLifestyle: false,
  },
  {
    name: "Pearl Grey",
    slug: "pearl-grey",
    series: "3",
    size: "3250 × 1650 × 20",
    isNew: true,
    microban: false,
    family: "grey",
    hasLifestyle: true,
  },
  {
    name: "Silver Grey",
    slug: "silver-grey",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "grey",
    hasLifestyle: false,
  },
  {
    name: "Milano",
    slug: "milano",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "grey",
    hasLifestyle: false,
  },
  {
    name: "Metropolitan",
    slug: "metropolitan",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "dark",
    hasLifestyle: true,
  },
  {
    name: "Ush",
    slug: "ush",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "dark",
    hasLifestyle: false,
  },
  {
    name: "Nero Classic",
    slug: "nero-classic",
    series: "3",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "dark",
    hasLifestyle: false,
  },
  {
    name: "Crema Verona",
    slug: "crema-verona",
    series: "2",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: true,
    family: "beige",
    hasLifestyle: true,
  },
  {
    name: "Bianco Diamante",
    slug: "bianco-diamante",
    series: "2",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "white",
    hasLifestyle: true,
  },
  {
    name: "Beige Diamante",
    slug: "beige-diamante",
    series: "2",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "beige",
    hasLifestyle: true,
  },
  {
    name: "Sandy Diamante",
    slug: "sandy-diamante",
    series: "2",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "beige",
    hasLifestyle: false,
  },
  {
    name: "Mocca Creme",
    slug: "mocca-creme",
    series: "2",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "beige",
    hasLifestyle: false,
  },
  {
    name: "Desert Brown",
    slug: "desert-brown",
    series: "2",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "dark",
    hasLifestyle: true,
  },
  {
    name: "Beige Tuscany",
    slug: "beige-tuscany",
    series: "2",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "beige",
    hasLifestyle: false,
  },
  {
    name: "Mocca Diamante",
    slug: "mocca-diamante",
    series: "2",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "dark",
    hasLifestyle: false,
  },
  {
    name: "Jerusalem Diamante",
    slug: "jerusalem-diamante",
    series: "2",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "grey",
    hasLifestyle: false,
  },
  {
    name: "Grigio Diamante",
    slug: "grigio-diamante",
    series: "2",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "grey",
    hasLifestyle: false,
  },
  {
    name: "Nero Diamante",
    slug: "nero-diamante",
    series: "2",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "dark",
    hasLifestyle: true,
  },
  {
    name: "Bianco Neve",
    slug: "bianco-neve",
    series: "1 A",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: true,
    family: "white",
    hasLifestyle: true,
  },
  {
    name: "Bianco Cristallo",
    slug: "bianco-cristallo",
    series: "1",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "white",
    hasLifestyle: false,
  },
  {
    name: "New Grey",
    slug: "new-grey",
    series: "1",
    size: "3150 × 1450 × 20",
    isNew: true,
    microban: false,
    family: "grey",
    hasLifestyle: false,
  },
  {
    name: "New Beige",
    slug: "new-beige",
    series: "1",
    size: "3150 × 1450 × 20",
    isNew: true,
    microban: false,
    family: "beige",
    hasLifestyle: true,
  },
  {
    name: "Crema Scuro",
    slug: "crema-scuro",
    series: "1",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: false,
    family: "beige",
    hasLifestyle: true,
  },
  {
    name: "Grigio Scuro",
    slug: "grigio-scuro",
    series: "1",
    size: "3150 × 1450 × 20",
    isNew: false,
    microban: true,
    family: "grey",
    hasLifestyle: true,
  },
];

/* ------------------------------------------------------------------ */
/* Colour-family category pages - each owns ONE search query           */
/* (GOVERNANCE §1: one page, one primary query, no cannibalization).   */
/* ------------------------------------------------------------------ */

export type QuartzFamily = {
  id: QuartzShade["family"];
  /** URL segment under /kalingastone/quartz/colours/ */
  slug: string;
  label: string;
  /** The one primary query this category page owns. */
  query: string;
  /** Answer-first opening paragraph (40-80 words, GOVERNANCE §7). */
  intro: string;
};

export const quartzFamilies: QuartzFamily[] = [
  {
    id: "white",
    slug: "white-quartz",
    label: "White Quartz",
    query: "white quartz slabs UAE",
    intro:
      "White engineered quartz is the most specified surface colour in the UAE, and the deepest part of the KalingaStone range: crisp Bianco whites, warm off-whites and crystal-fine particulates across every series tier. All slabs are 20 mm, non-porous and NSF-certified food safe, stocked in Sharjah by Global Classic for supply across the Emirates.",
  },
  {
    id: "veined",
    slug: "marble-look-quartz",
    label: "Marble-Look Quartz",
    query: "calacatta and marble-look quartz UAE",
    intro:
      "Marble-look quartz gives the drama of Calacatta and Carrara veining with none of natural marble's porosity. These are KalingaStone's premium Series 6-7 designs - Calacatta Imperial, Calacatta Lazza, Bianco Oro and their siblings - engineered at 20 mm for kitchen islands, cladding and vanities, supplied UAE-wide from Sharjah stock.",
  },
  {
    id: "beige",
    slug: "beige-quartz",
    label: "Beige & Cream Quartz",
    query: "beige and cream quartz UAE",
    intro:
      "Cream and beige quartz carries the warm palette Gulf interiors are built on - sand, travertine and crema tones that pair with brass, walnut and warm plaster. KalingaStone's beige range spans economical Series 1 particulates to layered Series 5 designs, all 20 mm, stain-proof and heat resistant, stocked in Sharjah.",
  },
  {
    id: "grey",
    slug: "grey-quartz",
    label: "Grey Quartz",
    query: "grey quartz slabs UAE",
    intro:
      "Grey is the working palette of contemporary UAE architecture - concrete, fjord and pietra tones that read equally well in matt and polished schemes. The KalingaStone grey range is the widest single colour family in the collection, from pale silver particulates to deep charcoal designs, every slab 20 mm and non-porous.",
  },
  {
    id: "dark",
    slug: "black-quartz",
    label: "Black & Dark Quartz",
    query: "black quartz slabs UAE",
    intro:
      "Black quartz makes the strongest single statement a countertop can: deep nero grounds, sparkling galaxy particulates and dramatic dark veining. KalingaStone's dark range is engineered like the rest of the collection - 20 mm, water absorption under 0.05%, impervious to heat - and supplied across the UAE from Global Classic's Sharjah stock.",
  },
];

export const familyBySlug = new Map(quartzFamilies.map((f) => [f.slug, f]));
export const familyById = new Map(quartzFamilies.map((f) => [f.id, f]));

export const shadeBySlug = new Map(quartzShades.map((s) => [s.slug, s]));

export const shadesOfFamily = (id: QuartzShade["family"]) =>
  quartzShades.filter((s) => s.family === id);

/** Catalogue order (Series 7 → 1) - the axis for prev/next pagination. */
export const shadeIndex = new Map(quartzShades.map((s, i) => [s.slug, i]));
